language: php

#versions
php:
#  - '5.4'
#  - '5.5'
#  - '5.6'
  - '7.0'
#  - hhvm
#  - nightly

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  #- composer update
  - composer install --prefer-dist --no-interaction
  #- find . -type f -name *.csv -exec chmod 777 {} +
  #- mkdir build


#script: phpunit tests/*
script:
  #script to setup the package for testing
  - phpunit --configuration phpunit.xml --debug  --coverage-text
  - phpunit
  - php -r 'echo __DIR__ . "\n";print_r(scandir(__DIR__));'

after_script:
  #- php vendor/bin/coveralls -v

notifications:
  email: false
